### ISSUE TITLE
lab: Overview tabs are inconsistents

### ISSUE THREAD

**Issue by gabrielmocanu** [open-education-hub/operating-systems#107]
The overview tabs for each chapter are inconsistent.
For example, for [compute], [io] and [app-interaction] contains only a table of content, but the [software-stack] and [data] contain beside the table of content some introduction information.
I don't know how it's better, but I think it should be a difference between **Overview** and **Introduction** and this should be consistent throughout all chapters.

Also, the setup part for Git should be removed right now since we have the base `support` directory for every lab.

[compute]: https://open-education-hub.github.io/operating-systems/Lab/Compute/Overview/content/overview
[io]: https://open-education-hub.github.io/operating-systems/Lab/I/O/Overview/content/overview
[app-interaction]: https://open-education-hub.github.io/operating-systems/Lab/Application-Interaction/Overview/content/overview
[software-stack]: https://open-education-hub.github.io/operating-systems/Lab/Software-Stack/Overview/content/overview
[data]: https://open-education-hub.github.io/operating-systems/Lab/Data/Overview/content/overview

**Comment by teodorjuravlea** [comment]
I propose moving the setup section that explains how to clone the repo to a chapter of it's own with a name to the likes of "Setting up the lab environment", and then having only one introduction chapter for every lab (either "Introduction" or "Overview") that contains a short summary and the list of contents.

**Comment by gabrielmocanu** [comment]
@teodorjuravlea 
This is good IMO.

@teodutu @Alex-deVis 
What do you think?

**Comment by teodutu** [comment]
Yup, sounds good. Looking forward to seeing a PR on this soon :wink:.

**Comment by teodorjuravlea** [comment]
I think this issue should be closed now.
