### ISSUE TITLE
software-stack/lab: Explain syscalls

### ISSUE THREAD

**Issue by teodutu** [open-education-hub/operating-systems#114]
The [Basic Syscalls](https://open-education-hub.github.io/operating-systems/Lab/Software-Stack/Basic%20System%20Calls/content/basic-syscall) chapter in the Software Stack lab starts very abruptly by showcasing the x86_64 syscall API without saying what a syscall is, why it needs to be performed etc.

This should be addressed by adding a paragraph (together with some diagrams if possible) stating the reason syscalls are important, what they do and why we need them before the [`Basic System Calls` section](https://github.com/open-education-hub/operating-systems/blob/master/content/chapters/software-stack/lab/content/basic-syscall.md#basic-system-calls). These details should be added to a new section.

**Comment by gabrielmocanu** [comment]
Just for reference, I think that the diagrams in [slides] 4-5 are quite good and we could use them.

[slides]: https://olivierpierre.github.io/linux-kernel-programming/slides/04_SystemCalls.pdf
