### ISSUE TITLE
compute/lab: Replace Scheduling section with User-level Threads

### ISSUE THREAD

**Issue by teodutu** [open-education-hub/operating-systems#130]
[`libult`](https://github.com/open-education-hub/operating-systems/tree/master/content/chapters/compute/lab/support/libult) is both buggy  as described in https://github.com/open-education-hub/operating-systems/issues/51 and difficult to understand. The purpose of this exercise and section is to visualise user-level threads. This can be done a lot easier using either:

- [goroutines](https://go.dev/tour/concurrency/1) in Go
- [fibres in D](https://tour.dlang.org/tour/en/multithreading/fibers). The advantage of D fibres is that D is similar enough to C so the overhead from switching languages is smaller. Another useful explanation can be found [here](https://ocw.cs.pub.ro/courses/dss/laboratoare/05#fibers).

Pick one user-level thread implementation and replace [`libult`](https://open-education-hub.github.io/operating-systems/Lab/Compute/Scheduling/content/scheduling#practice-user-level-threads-scheduler) with it. The new exercise should focus on the functionality of user-level threads and not on their implementation. The [Scheduling section](https://open-education-hub.github.io/operating-systems/Lab/Compute/Scheduling/content/scheduling) needs to be replaced with "User-level Threads" in accordance with the changes above.

**Comment by cristian-vijelie** [comment]
How about [libfibre](https://git.uwaterloo.ca/mkarsten/libfibre) with C/C++?

**Comment by cristian-vijelie** [comment]
Also, this is a good time to use cmake

**Comment by teodutu** [comment]
> How about [libfibre](https://git.uwaterloo.ca/mkarsten/libfibre) with C/C++?

This is also a viable option. The advantage of presenting ULTs that are built into a language (or at least part of its official ecosystem) is that this involves less overhead, a lower risk of things not working (like `libult`) and pushes the idea that each language is built with a certain purpose in mind (like networking in microservices is for Go).

I'm not sure which path to take. @gabrielmocanu, @Alex-deVis, what do you think? @edi33416, you proposed this change. What's your opinion?

**Comment by Alex-deVis** [comment]
I prefer C/C++, as we decided to use it as the backbone of our exercises.

**Comment by teodutu** [comment]
Ok, I guess libfire should be fine then. @cristian-vijelie go ahead and add it. You can mention in the Markdown file that languages such as Go offer this functionality as a builtin.

**Comment by teodutu** [comment]
Bump @cristian-vijelie.

**Comment by edi33416** [comment]
I think we should probably use a more popular (and probably better maintained) solution like boost's [Fiber](https://www.boost.org/doc/libs/1_80_0/libs/fiber/doc/html/index.html) or Facebook's [folly](https://github.com/facebook/folly/tree/main/folly/fibers).

**Comment by teodutu** [comment]
[Fiber](https://www.boost.org/doc/libs/1_80_0/libs/fiber/doc/html/index.html) or [folly](https://github.com/facebook/folly/tree/main/folly/fibers) make more sense than `libfire`. Try using these libraries @cristian-vijelie.
