### ISSUE TITLE
io/{lab,lecture}: Add demo using `lsof` while spawning multiple browser tabs

### ISSUE THREAD

**Issue by teodutu** [open-education-hub/operating-systems#135]
The sockets opened by each browser tab can be inspected using `lsof`. This behaviour is merely mentioned [here](https://open-education-hub.github.io/operating-systems/Lab/IO/remote-io/#further-than-ips-ports), but no demo is provided. Both the lab and the lecture would benefit from having a demo where `lsof` is running while opening several firefox tables.

**Comment by Alex-deVis** [comment]
I don't know what you have in mind. I attempted this demo using both `lsof` and `ls -l proc/pid/fd`; neither yielded an example easy to follow.
The principle is good: firefox will create a new `fd` for each new tab, but it will also create additional file descriptors: UNIX sockets, FIFOs, and regular files for caching. The big problem is that the number and kind of additional descriptors vary.

Making sense of these events by limiting output would mean making a plain, theoretical demo, that requires extra work from the students to reproduce.
I would rather keep the simple principle that one tab equals a new file descriptor, and expect them to anticipate that in practice things are not as simple.

**Comment by teodutu** [comment]
Yeah, you're correct. I'm closing this as I assumed this would be more straightforward, but looking into the problem myself, it's quite messy and difficult to separate the wheat from the chaff. :cry:
