### ISSUE TITLE
util: Add CI action to build the docker image for AMD and ARM platforms

### ISSUE THREAD

**Issue by teodutu** [open-education-hub/operating-systems#155]
As suggested in [this comment](https://github.com/open-education-hub/operating-systems/pull/149#issuecomment-1454147338), the current docker image needs to be built for AMD and ARM architectures separately and then pushed to a container registry (I suggest GitHub's own registry to keep things open and available). To do so, follow the example [here](https://github.com/edi33416/docker-buildx-ci/blob/main/.github/workflows/ci.yml).

**Comment by darius-m** [comment]
Please prioritize this part. The system updates (using `apt update`) take an extremely long time (some users' build times out completely).
