### ISSUE TITLE
Create a comprehensive guide for Docker installation

### ISSUE THREAD

**Issue by RaduNiculae** [open-education-hub/operating-systems#160]
Create a step by step guide for Docker installation and container start.
It should include WSL installation and setup to work with Docker.

**Comment by Alex-deVis** [comment]
It only makes sense for the guide to be added in the `README.md` from `util/os-runner`. The added section could cover prerequisites for Windows.

**Comment by Alex-deVis** [comment]
The repository should be cloned directly in WSL or the bind mount will not work.
