### ISSUE TITLE
Error docker

### ISSUE THREAD

**Issue by elenaulariu** [open-education-hub/operating-systems#167]
ERROR [internal] load metadata for docker.io/library/ubuntu:20.04 0.2s ------ > [internal] load metadata for docker.io/library/ubuntu:20.04: ------ failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fubuntu%3Apull&service=registry.docker.io": dial tcp: lookup auth.docker.io on 172.23.176.1:53: dial udp 172.23.176.1:53: connect: network is unreachable make: *** [Makefile:9: docker-image] Error 1

**Comment by darius-m** [comment]
The "dial tcp: lookup auth.docker.io [...] connect: network is unreachable" likely means that your system either does not have internet access or fails the DNS lookup. Please make sure that you can access the internet to fetch the containers.
