### ISSUE TITLE
util: Docker makefile dependencies do not work

### ISSUE THREAD

**Issue by darius-m** [open-education-hub/operating-systems#169]
Makefiles are meant to track file changes. so a rule that looks like `binary: code.c` will run the instructions to build `binary` whenever `binary` is older (has an older change time) than `code.c`.

For the code in the [os-runner/Makefile](https://github.com/open-education-hub/operating-systems/blob/master/util/os-runner/Makefile#L11) the `start` and `attach` rules depend on the `docker-image` rule that does not have any dependencies. As such, the build rule runs whenever the `attach` rule is used.

`docker-compose` is the proper way to handle container builds, and comes with rules to build, start and attach to containers, while properly tracking if changes are required.

**Comment by teodutu** [comment]
CC @Alex-deVis.

**Comment by Alex-deVis** [comment]
Valid points, @darius-m. PR https://github.com/open-education-hub/operating-systems/pull/168 addresses the dependency problems in the Makefile. Please take a look and leave suggestions there. With these changes, I think `docker-compose` is not needed.

**Comment by darius-m** [comment]
The PR appears to address the issues, but it abuses makefiles quite a bit. While it works, it adds few manual checks that could probably be done automatically by docker-compose. However, it should fix the issue.
