### ISSUE TITLE
software-stack/lab: perf not working on docker

### ISSUE THREAD

**Issue by radudum10** [open-education-hub/operating-systems#184]
```shell
🐳 student@os:~$ perf --version
WARNING: perf not found for kernel 6.1.11

  You may need to install the following packages for this specific kernel:
    linux-tools-6.1.11-200.fc37.x86_64
    linux-cloud-tools-6.1.11-200.fc37.x86_64

  You may also want to install one of the following packages to keep up to date:
    linux-tools-200.fc37.x86_64
    linux-cloud-tools-200.fc37.x86_64
```
* The mentioned packets can't be installed.
* The following answer should solve this: https://askubuntu.com/a/753796

**Comment by Alex-deVis** [comment]
@craciunoiuc attempted to solve this with https://github.com/open-education-hub/operating-systems/pull/185, you can find the details there.

In summary, `perf` from docker depends on `perf` from the host and there is no easy way to ensure compatibility for all hosts.
We should tag all `perf` demos with `to be run on host`. I will close this issue when this happens.
