### ISSUE TITLE
Copy constructor is not being called

### ISSUE THREAD

**Issue by vladtf** [open-education-hub/operating-systems#234]
This line doesn't seem to be considered as a copy construct call: https://github.com/open-education-hub/operating-systems/blob/20f4323efdcfb06e3a00e1ae0759d65f7446f8c3/content/chapters/data/lab/support/reference-counting/operators.d#L42

To make it working I used the following call:
```
Obj o3 = Obj(o1);
```

**Comment by tudorcondrea** [comment]
Hello,
`gdc` compiler optimizes the code and removes the line that should call the copy constructor.
I compiled using `dmd refcount_skel.d -of=refcount_skel` instead and it preserves the line that calls the copy constructor and the exercises can be done properly.

**Comment by teodutu** [comment]
@vladtf what compiler were you using?

I've tested `dmd` and `gdc` and @tudorcondrea's observation holds. I also tested `ldc` and the behaviour is as expected: the copy constructor is called. To me this looks more like a `gdc` error.

**Comment by vladtf** [comment]
Hi @teodutu. This is the config the version of the gdc in docker container:
```
 student@os:~$ gdc --version
gdc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by vladtf** [comment]
@tudorcondrea, I don't think these is the reason. I added some code to be sure that this line won't be removed during optimisation and the copy constructor is still not being used.
```
    writeln("constructor call");
    Obj o1 = 1;                     // => rewritten to `Obj o1 = Obj(1);`

    writeln("copy constructor call");
    Obj o2 = o1;                    // => rewritten to `Obj o2 = Obj(o1);`
    o2.a = 2;
    writeln(o2.a);
```

Output:
```
constructor call
---calling constructor
copy constructor call
2
assignment operator call
```

**Comment by RazvanN7** [comment]
> Output:

@vladtf  In your output I see a copy constructor call. What is the problem?

**Comment by teodutu** [comment]
> > Output:
> 
> @vladtf In your output I see a copy constructor call. What is the problem?

It's not. The output shows the text printed by this `writeln()` [1], but not the one coming from the copy constructor [2].

[1] https://github.com/open-education-hub/operating-systems/blob/50ec5ba6d83fb9712a81085e5d0aef02ad8ea9c8/content/chapters/data/lab/support/reference-counting/operators.d#L41
[2] https://github.com/open-education-hub/operating-systems/blob/50ec5ba6d83fb9712a81085e5d0aef02ad8ea9c8/content/chapters/data/lab/support/reference-counting/operators.d#L18

**Comment by vladtf** [comment]
> ldc

This how the message is looking the lab support:
```   
 // copy constructor
  this(ref Obj obj)
  {
      writeln("---calling copy constructor");
  }
```

Therefore, right after the `copy constructor call` it should have been displayed `---calling copy constructor`

**Comment by RazvanN7** [comment]
Ok, so it's not a gdc error. It's just that gdc10 does not support the copy constructor. gdc10 implements version 2.076 of the D frontend, whereas the copy constructor was added in version 2.086 [1]. We need gdc12 [2], which implements 2.100 at least, to be able to use the copy constructor. However, using dmd/ldc should be fine.

[1] https://dlang.org/changelog/2.086.0.html#copy_constructor
[2] https://gcc.gnu.org/gcc-12/changes.html

**Comment by Alex-deVis** [comment]
@RazvanN7 should we keep this issue open until we either change the output or update the `gdc` version in the `Dockerfile`?

**Comment by teodutu** [comment]
> @RazvanN7 should we keep this issue open until we either change the output or update the `gdc` version in the `Dockerfile`?

A better question is why do we install `gdc` in the container?

**Comment by Alex-deVis** [comment]
> A better question is why do we install gdc in the container?

The `Dockerfile` follows dependencies listed by the `Makefile`s in the project. Update all `Makefile`s to use `dmd`, check the code and remove `gdc` from the `Dockerfile` .

**Comment by RazvanN7** [comment]
Initially, before we considered using a dockerfile, I thought it would be easier to use gdc since it is distributed with gcc.

**Comment by RazvanN7** [comment]
Well, that's true for dmd as well, no?

**Comment by teodutu** [comment]
For `dmd` it's done automatically because this script [1] installs the latest version when building the container. We can use it to install either `gdc` or `ldc`. We should decide which one and be consistent.

[1] https://github.com/open-education-hub/operating-systems/blob/master/util/os-runner/install-dmd.sh
