### ISSUE TITLE
`data/lab`: `./benchmark_cp.sh` does not work with Docker

### ISSUE THREAD

**Issue by Iulian277** [open-education-hub/operating-systems#261]
Running the `./benchmark_cp.sh` script on Docker, throws the following error:

```
sh: 1: cannot create /proc/sys/vm/drop_caches: Read-only file system
Benchmarking mmap_copy on in.dat
time passed 29191 microseconds

sh: 1: cannot create /proc/sys/vm/drop_caches: Read-only file system
Benchmarking read_write_copy on in.dat
time passed 38918 microseconds
```

If I run the script on wsl2 (without docker attached), everything runs smoothly:

```
Benchmarking mmap_copy on in.dat
time passed 3638965 microseconds

Benchmarking read_write_copy on in.dat
time passed 191309 microseconds
```

**Comment by teodutu** [comment]
Did you install `docker` using snap or using the [official instructions](https://docs.docker.com/engine/install/ubuntu/). Make sure you do it using the latter approach.

**Comment by Alex-deVis** [comment]
> Make sure you do it using the latter approach.

Or with this script: https://get.docker.com.

**Comment by Iulian277** [comment]
I have installed Docker Desktop on Windows and used the `wsl 2 backed engine`.
After cloning this repo, I started and attached a docker image using the commands `make start` and `make attach`.

**Comment by gabrielmocanu** [comment]
@teodutu @Alex-deVis 

It's a real problem. 
@Iulian277  run this script from the container, since the container doesn't have permission to write to `/proc/sys/vm/drop_caches` it throws out this error.
The solution would be to run that script locally.

@Iulian277  can you make a PR and solve this one by adding a note to run this script from local environment without using the container?

**Comment by teodutu** [comment]
> the container doesn't have permission to write to /proc/sys/vm/drop_caches

This is what I don't yet understand. Why isn't the container allowed to write to `/proc/sys/vm/drop_caches`?

**Comment by gabrielmocanu** [comment]
> > the container doesn't have permission to write to /proc/sys/vm/drop_caches
> 
> This is what I don't yet understand. Why isn't the container allowed to write to `/proc/sys/vm/drop_caches`?

https://unix.stackexchange.com/a/209361/503407

**Comment by teodutu** [comment]
> https://unix.stackexchange.com/a/209361/503407

I see. That's sad. Thanks.

**Comment by gabrielmocanu** [comment]
> > https://unix.stackexchange.com/a/209361/503407
> 
> I see. That's sad. Thanks.

Maybe there are other solutions for this, but I didn't had time to investigate.
