### ISSUE TITLE
software-stack/libcall-syscall: `ltrace` doesn't show library calls at all

### ISSUE THREAD

**Issue by mariasfiraiala** [open-education-hub/operating-systems#27]
`ltrace` works by extracting stuff out of the PLT, so if `binutils` is optimizing a `PLT` access into a `GOT` access (by relying on `now binding`) it's likely that `ltrace` is going to stop working.

I've tested this on 2 quite different Debian based distros:

## Ubuntu 20.04

| bin | version |
|-----|---------|
| gcc | 9.4.0|
| ld | 2.34 |

The main question is why are binaries linked with the `-z now` flag (`now binding`) on Ubuntu.

Even when trying to inspect `/bin/ls`, there is no output for `ltrace`:

```
$ scanelf -a /bin/ls
 TYPE    PAX   PERM ENDIAN STK/REL/PTL TEXTREL RPATH BIND FILE 
ET_DYN PeMRxS 0755 LE RW- R-- RW-    -      -   NOW /bin/ls 

```

```
$ ltrace /bin/ls
issues-ltrace.md
+++ exited (status 0) +++
```

## ParrotOS

| bin | version |
|-----|---------|
| gcc | 10.2.1 |
| ld | 2.35.2 |

On my ParrotOS machine (a Debian based rolling distro), binaries are linked by default with `-z lazy`, ergo, `ltrace` works like expected:

```bash
$ scanelf -a /bin/ls
 TYPE    PAX   PERM ENDIAN STK/REL/PTL TEXTREL RPATH BIND FILE 
ET_DYN PeMRxS 0755 LE RW- R-- RW-    -      -   LAZY /bin/ls
```

```bash
$ ltrace /bin/ls
strrchr("/bin/ls", '/')                          = "/ls"
setlocale(LC_ALL, "")                            = "LC_CTYPE=en_US.UTF-8;LC_NUMERIC="...
bindtextdomain("coreutils", "/usr/share/locale") = "/usr/share/locale"
textdomain("coreutils")                          = "coreutils"
__cxa_atexit(0x56359a85d5a0, 0, 0x56359a873368, 0) = 0
isatty(1)                                        = 1

[...]

+++ exited (status 0) +++
```
### Further explaining the issue

* https://stackoverflow.com/questions/43213505/no-output-when-running-ltrace

* https://sourceware.org/legacy-ml/binutils-cvs/2015-05/msg00106.html

* https://bugzilla.redhat.com/show_bug.cgi?id=1333481

* https://stackoverflow.com/questions/58076539/plt-plt-got-what-is-different

### Fixing the issue

* https://github.com/namhyung/uftrace/issues/592

>This change will enable tracing library calls have no PLT. As PLT is needed to trace those libcalls, uftrace make up a trampoline and fill necessary instructions there.
The code is available at [review/libcall-noplt-v1](https://github.com/namhyung/uftrace/compare/review/libcall-noplt-v1) branch.

* https://stackoverflow.com/questions/61394462/alternative-to-ltrace-that-works-on-binaries-linked-with-z-now?noredirect=1&lq=1

## Quick fixes on Ubuntu

I've found 2 alternative hacks:

* Installed and used the `uftrace` tool:

```bash
$ sudo apt install uftrace

$ uftrace --force /usr/bin/pwd
/home/maria/Documents/school-work/SO/my-so-lab-2022/software-stack/libcall-syscall
# DURATION     TID     FUNCTION
   2.766 us [ 26498] | getenv();
   0.160 us [ 26498] | strrchr();
  82.619 us [ 26498] | setlocale();
   0.591 us [ 26498] | bindtextdomain();
   0.742 us [ 26498] | textdomain();
   0.241 us [ 26498] | __cxa_atexit();
   4.511 us [ 26498] | getopt_long();
   7.036 us [ 26498] | getcwd();
  15.686 us [ 26498] | puts();
   0.170 us [ 26498] | free();
   0.241 us [ 26498] | __fpending();
   0.261 us [ 26498] | fileno();
   0.241 us [ 26498] | __freading();
   0.100 us [ 26498] | __freading();
   0.621 us [ 26498] | fflush();
   1.273 us [ 26498] | fclose();
   0.110 us [ 26498] | __fpending();
   0.110 us [ 26498] | fileno();
   0.111 us [ 26498] | __freading();
   0.090 us [ 26498] | __freading();
   0.120 us [ 26498] | fflush();
   0.592 us [ 26498] | fclose();
```

* Modified the Makefile (for the required exercise) in order to force the lazy binding:

```patch
diff --git a/content/chapters/software-stack/lab/support/libcall-syscall/Makefile b/content/chapters/software-stack/lab/support/libcall-syscall/Makefile
index bd91a72..a91df3f 100644
--- a/content/chapters/software-stack/lab/support/libcall-syscall/Makefile
+++ b/content/chapters/software-stack/lab/support/libcall-syscall/Makefile
@@ -1,4 +1,5 @@
 CFLAGS = -Wall
+LDFLAGS = -z lazy
 
 .PHONY: all clean
```

```bash
$ ltrace ./call
fopen("a.txt", "wt")                             = 0x5603b16fb2a0
strlen("Hello, world!\n")                        = 14
fwrite("Hello, world!\n", 1, 14, 0x5603b16fb2a0) = 14
fflush(0x5603b16fb2a0)                           = 0
+++ exited (status 0) +++
```

The second alternative does half of the work, as we cannot change binaries that are already compiled (e.g. `/bin/pwd`).

**Comment by darius-m** [comment]
An alternative would be calling `ltrace` using `-x "pattern"` to print library calls that match a certain library. The pattern can also be `*` for all library calls, in all libraries. See this answer for some basic examples https://stackoverflow.com/a/67719792.

**Comment by mariasfiraiala** [comment]
> An alternative would be calling `ltrace` using `-x "pattern"` to print library calls that match a certain library. The pattern can also be `*` for all library calls, in all libraries. See this answer for some basic examples https://stackoverflow.com/a/67719792.

Thanks a lot @darius-m , works. Is it a good idea to integrate either one of my hacks or this one in the lab content? It would make things less confusing.

From my point of view, the fix that changes the `Makefile` in order to force the lazy binding is the easiest one to implement.

**Comment by darius-m** [comment]
I personally find that the lazy binding approach would be the easiest and most transparent, but will hide some complexity from people who will be confused if the tool does not work outside our examples (like we were when we first saw this). Using either `uftrace` or the `-x` flag would provide a more universal solution to the issue.

The issue with `uftrace` is that (judging from the output you have provided) it is meant as a more performance oriented tracer (similar to, for example, perf). It provides some info on the time a function took to run, but does not show (at least by default) the parameters the function calls take, so it is less useful for something like reverse engineering.

The disadvantage of using `-x` is, of course, the rather ridiculously large output, since it shows all function calls inside the library. A simple "Hello world" program should output a single line (that contains a single `gets` library call), but will instead display over 80 lines (may differ depending on the system, but it is still a lot more than what someone would normally be interested in).

@razvand  what do you think?

**Comment by razvand** [comment]
@darius-m , @mariasfiraiala , what we should strive for is consistency / uniformity: minimal number of changes that makes things work similarly across executables, distros, etc. Fortunately, it seems, [all is OK for future ltrace versions](https://stackoverflow.com/a/74784223/4804196) so hopefully the issue will not manifest itself in the fure.

My first thought is to use the `-x` approach suggested by @darius-m . But I'm running it on Ubuntu 18.04 and on Ubuntu 20.04 and it doesn't behave the same:

**Ubuntu 18.04**

```console
$ ltrace -x 'malloc' /bin/ls
[...]
fclose(0x7f9bd829c760)                                                                                           = 0
__fpending(0x7f9bd829c680, 0, 0x7f9bd8297760, 2880)                                                              = 0
fileno(0x7f9bd829c680)                                                                                           = 2
__freading(0x7f9bd829c680, 0, 0x7f9bd8297760, 2880)                                                              = 0
__freading(0x7f9bd829c680, 0, 4, 2880)                                                                           = 0
fflush(0x7f9bd829c680)                                                                                           = 0
fclose(0x7f9bd829c680)                                                                                           = 0
+++ exited (status 0) +++
```

**Ubuntu 20.04**

```console
$ ltrace -x 'malloc' /bin/ls
[...]
malloc@libc.so.6(11)                                                                                             = 0x5582c7317ee0
malloc@libc.so.6(26)                                                                                             = 0x5582c7317f00
malloc@libc.so.6(8)                                                                                              = 0x5582c7317f30
malloc@libc.so.6(12)                                                                                             = 0x5582c7317f50
malloc@libc.so.6(960)                                                                                            = 0x5582c730f9c0
malloc@libc.so.6(1464)                                                                                           = 0x5582c730fd90
malloc@libc.so.6(15128)                                                                                          = 0x5582c7310350
malloc@libc.so.6(1024)                                                                                           = 0x5582c7309500
[...]
```

If we can't get `-x` to behave consistently, we use the `-z lazy` approach suggested by @mariasfiraiala . And we make notes as part of the lab text, that system executables may not work under `ltrace` (if built `-z now`); and we suggest using `ltrace -x` for those.

**Comment by darius-m** [comment]
Unfortunately, some stable distributions tend to stick to a certain version of an application for a long(er) periods of time, so the updated version may still be an issue in the future; versions like Ubuntu 18.04 that approach EOL are especially unlikely to update their packages. The lazy binding appears to be the cleanest approach, since it should cause the least number of different outputs depending on the version (probably unless `-x '*'` is used, but the output is a lot harder to parse in that case).

**Comment by razvand** [comment]
@mariasfiraiala , then it's settled. Update to `-z lazy` wherever there is a use of `ltrace`. I think there are other chapters besides `software-stack` that used `ltrace`. And, the first time we use `ltrace` (in the `software-stack` section), make a note about system executables that may not work, if built with `-z now`.

**Comment by mariasfiraiala** [comment]
Thank you @razvand @darius-m for the insights. I'll start making the necessary changes and come back with a PR for them.

**Comment by bernhardkaindl** [comment]
@darius-m, you wrote:
> The issue with uftrace is that (judging from the output you have provided) it is meant as a more performance oriented tracer (similar to, for example, perf). It provides some info on the time a function took to run, but does not show (at least by default) the parameters the function calls take, so it is less useful for something like reverse engineering.

@mariasfiraiala didn't add the flags `-A. -R.` to show all function call arguments and function call return values:
```py
uftrace -A. -R. --force pwd
/home/t_bernhardk
# DURATION     TID     FUNCTION
 483.385 us [384739] | getenv("POSIXLY_CORRECT") = "NULL";
   2.107 us [384739] | strrchr("pwd", '/') = "NULL";
  76.140 us [384739] | setlocale(LC_ALL, "") = "en_US.UTF-8";
   2.972 us [384739] | bindtextdomain("coreutils", "/usr/share/locale");
   3.703 us [384739] | textdomain("coreutils");
   1.334 us [384739] | __cxa_atexit();
   4.173 us [384739] | getopt_long(1, 0x7ffcb5cabbc8, "LP") = -1;
   8.990 us [384739] | getcwd(0, 0) = "/home/t_bernhardk";
  25.132 us [384739] | puts("/home/t_bernhardk") = 18;
   2.325 us [384739] | free(0x55cf744e9bd0);
   1.122 us [384739] | __fpending();
   2.552 us [384739] | fileno(&_IO_2_1_stdout_) = 1;
   1.338 us [384739] | __freading();
   1.352 us [384739] | __freading();
   1.479 us [384739] | fflush(&_IO_2_1_stdout_) = 0;
   3.396 us [384739] | fclose(&_IO_2_1_stdout_) = 0;
   0.723 us [384739] | __fpending();
   1.364 us [384739] | fileno(&_IO_2_1_stderr_) = 2;
   1.318 us [384739] | __freading();
   1.315 us [384739] | __freading();
   1.385 us [384739] | fflush(&_IO_2_1_stderr_) = 0;
   2.718 us [384739] | fclose(&_IO_2_1_stderr_) = 0;
```
In comparison to `ltrace`
- the output is using colors to hightlight the arguments if output is a terminal,
- the FILE pointers for stdin, stdout and stderr are shown symbolically,
- and (IMHO) the output is much more readable.
