### ISSUE TITLE
Ignore `WARNING:REPEATED_WORD` in checkpatch action

### ISSUE THREAD

**Issue by cristian-vijelie** [open-education-hub/operating-systems#292]
It seems checkpatch doesn't like Lorem Ipsum.

**Comment by teodutu** [comment]
I think the warning is useful in general. We can ignore it locally if we need to, via a `.checkpatch.conf` file.

**Comment by Alex-deVis** [comment]
> We can ignore it locally if we need to, via a .checkpatch.conf file.

Agreed. @teodutu any reason to keep this open?

**Comment by teodutu** [comment]
None.

**Comment by teodutu** [comment]
None
