### ISSUE TITLE
<thread> is an unapproved C++11 header.

### ISSUE THREAD

**Issue by cristian-vijelie** [open-education-hub/operating-systems#293]
From discussions I found, it seems that Google has a preference for other headers (re2). Their preference shouldn't affect us, though.

**Comment by teodutu** [comment]
Provide links to those discussions. What is the problem with `<thread>`? For reference, re2 is: https://github.com/google/re2.

**Comment by cristian-vijelie** [comment]
Sorry, re2 is used instead of <regex>. I don't know what they don't like about <thread>

https://github.com/google/styleguide/issues/194

**Comment by teodutu** [comment]
The comments in the issues you've linked give little reason for this "preference". Just remove that filter locally (via a `CPPLINT.cfg` file) for the affected code in #291 and that should be fine.
