### ISSUE TITLE
Docusaurus Lab App-Interaction

### ISSUE THREAD

**Issue by RMProg** [open-education-hub/operating-systems#79]
Capitolu SO-Cloud este vizibil strict din pagina Overview, din pagina generala a laboratorului nu poate fi vazuta.
De asemenea, nu se poate da next din capitolul anterior.

**Comment by teodutu** [comment]
This is fine. That chapter is still a work in progress and will be released at the beginning of 2023, as part of the second half of the App-Interaction chapter. It is visible in the [Overview page](https://open-education-hub.github.io/operating-systems/Lab/Application-Interaction/Overview/content/overview) in case you are curious about it before the lab itself, but the task is not finished yet.
